### ISSUE TITLE
Incorrect domain in your blacklist

### ISSUE THREAD

**Issue by ronkol** [Marfjeh/coinhive-block#24]
https://github.com/Marfjeh/coinhive-block/blob/e146a91a4a5046f47b599ed1899dce05493cec0d/domains#L4084

My name is Ron Kol, VP R&D of Hola Spark http://holaspark.com. We are a worldwide service provider of CDN and Video experience enhancements and have top tier customers as you can see on our site.

In this commit you added player.h-cdn.com to your blacklist. I have no idea why but this is hurting our reputation and business.

Please remove us from this list or tell me why we are on it so we can get it resolved.

Thanks,

**Comment by Marfjeh** [comment]
Hello. Sorry for the inconvenience the domain was added from an different list that is not made by me. the list was merged with the one we made here. and i'll remove the url.

Sorry i didnt respond that fast. there was alot of things happening in my life.

**Comment by megaxlr** [comment]
Hello.
As Marf has pointed out, this domain was contributed and not found by us.

I don't want to tell you how to run your business, but I would personally take a thorough look at the content you might be hosting. Could there be a crypto miner file?

I will personally audit our list closer in the future as I am completing an automated system to curate the list.

Thank you for your report
 - MegaXLR

**Comment by ronkol** [comment]
Thanks. There is absolutely no miner anywhere in our code and never was. 

It’s enough that there is one false report and then it spreads like fire as you guys just copy from each other without verification.

Now I don’t want to tell you how to run your business but you should reconsider that policy.

Ron
