### ISSUE TITLE
Adblock-friendly list and pre-generated hosts file.

### ISSUE THREAD

**Issue by Marfjeh** [Marfjeh/coinhive-block#25]
because i want to move from compilers to pre-generated hosts files. so that you dont need to compile your self on your local system because you cannot always compile it on your own system, for instance on your phone. 

The compilers are cool and they stay where they are but i'm going to add pre-generated hostfiles in the repo, so that you can use them in for example: Adway for android. Ublock orgin and other adblockers that support adblock lists.

**EDIT**
Added support in 8b901f6de68c049b2ae2e3a3d9e729132457c9d8

Adgaurd support yet to come. i do not use it myself, and i dont have a licence for it.

**Comment by TPS** [comment]
@ameshkov Whenever this lands, interested for AdGuard?

**Comment by Marfjeh** [comment]
note to self: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by Marfjeh** [comment]
also adding support for

* Pihole
* Adblockers, such as Adblock plus and ublock orgin etc. (that use the adblock format)
* Programs that understands hostfiles
* Android's adway app
* Android DNS66

**Comment by Marfjeh** [comment]
Added support in 8b901f6de68c049b2ae2e3a3d9e729132457c9d8

Adgaurd support yet to come. i do not use it myself, and i dont have a licence for it.

**Comment by Marfjeh** [comment]
it seems you can use the adblock list as well. but havent tested it.

**Comment by TPS** [comment]
>[Adguard] support yet to come. i do not use it myself, and __i dont have a licence for it.__
>
>it __seems__ you can use the adblock list as well. but havent tested it.

@ameshkov Would y'all provide @Marfjeh a license per https://adguard.com/en/rewards.html#anchor-0, & also _officially_ clarify for him how his lists can/will be used in various AG platforms?

**Comment by ameshkov** [comment]
Sure, just contact us at `devteam@adguard.com`
