### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by benjaminnichols** [Marfjeh/coinhive-block#4]
I have been told that xmrpool.eu is a legitimate mining site, but it is in your blacklist, but I am not certain,  you may opt to investigate.

**Comment by Marfjeh** [comment]
Hmm You're right, it is indeed a mining pool.
This is probably from a pull request, so i'll remove it.

Thanks for reporting!
-Marvin

**Comment by Marfjeh** [comment]
I have removed like multiple pools, but i'm not sure that i removed every false positives that aren't JS miners/proxys
