### ISSUE TITLE
Remove *.authedmine.com

### ISSUE THREAD

**Issue by Leseratte10** [Marfjeh/coinhive-block#5]
I'd advise you to remove *.authedmine.com from your blacklist. 

It is indeed operated by coinhive.com, but all the scripts on this domain ask the visitor for permission before mining, thus this can only be used for web page supporting, not malicious mining. 

In addition, this also provides a captcha-like alternative based on proof-of-work, not entering weird characters into a captcha box. 

For more information, you can read the notice on the web page itself ( http://authedmine.com )

**Comment by megaxlr** [comment]
This does seem more sane to me than coinhives other sites. Marf, what do you think? I agree on removing it from the blacklist.

**Comment by Marfjeh** [comment]
I really approve of this that they are asking users for mining and not doing it without the user knowledge. for me the concept for a alternative for advertising is great. only the execution of it is not. authedmine.com fixes this problem for JS miners.

**Comment by Marfjeh** [comment]
if you find more of those miners and they're in the block list, let me know.
