### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Fusl** [Marfjeh/coinhive-block#6]
Hi,

I'm using your block list to protect my laptop from mining cryptocurrencies for random websites, instead I'd like to donate some money to you directly for the efforts you put into this list. Do you have a BTC, BCH, XMR, PayPal, etc. address or any other way I can send you some money?

Thanks,
Fusl

**Comment by Marfjeh** [comment]
Sure! I've added a paypal button on the bottom on the readme.md, 
Sorry for this late comment, i was very busy haha.
